/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_flightSim_wrapper_FSWrapper */

#ifndef _Included_com_flightSim_wrapper_FSWrapper
#define _Included_com_flightSim_wrapper_FSWrapper
#ifdef __cplusplus
extern "C" {
#endif
#undef com_flightSim_wrapper_FSWrapper_SIM_ANY
#define com_flightSim_wrapper_FSWrapper_SIM_ANY 0L
#undef com_flightSim_wrapper_FSWrapper_SIM_FS98
#define com_flightSim_wrapper_FSWrapper_SIM_FS98 1L
#undef com_flightSim_wrapper_FSWrapper_SIM_FS2K
#define com_flightSim_wrapper_FSWrapper_SIM_FS2K 2L
#undef com_flightSim_wrapper_FSWrapper_SIM_CFS2
#define com_flightSim_wrapper_FSWrapper_SIM_CFS2 3L
#undef com_flightSim_wrapper_FSWrapper_SIM_CFS1
#define com_flightSim_wrapper_FSWrapper_SIM_CFS1 4L
#undef com_flightSim_wrapper_FSWrapper_SIM_FS2K2
#define com_flightSim_wrapper_FSWrapper_SIM_FS2K2 6L
/*
 * Class:     com_flightSim_wrapper_FSWrapper
 * Method:    Open
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_flightSim_wrapper_FSWrapper_Open
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_flightSim_wrapper_FSWrapper
 * Method:    Close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_flightSim_wrapper_FSWrapper_Close
  (JNIEnv *, jclass);

/*
 * Class:     com_flightSim_wrapper_FSWrapper
 * Method:    ReadData
 * Signature: (II[B)V
 */
JNIEXPORT void JNICALL Java_com_flightSim_wrapper_FSWrapper_ReadData
  (JNIEnv *, jclass, jint, jint, jbyteArray);

/*
 * Class:     com_flightSim_wrapper_FSWrapper
 * Method:    WriteData
 * Signature: (II[B)V
 */
JNIEXPORT void JNICALL Java_com_flightSim_wrapper_FSWrapper_WriteData
  (JNIEnv *, jclass, jint, jint, jbyteArray);

/*
 * Class:     com_flightSim_wrapper_FSWrapper
 * Method:    Process
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_flightSim_wrapper_FSWrapper_Process
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
